### PR TITLE
Close files, and prevent reading subsequent, nonexistant files

### PR DESCRIPTION
**Pull request by brendanwhitfield**
Initially, readFastaChunks() tries to open every possible chunk it can, which can result in excessive looping. It now stops when a file is not found (no more data to be read). Also, for brevity, accumulation is done directly into `self.seq`

### CODE REVIEW

**Comment by josiahseaman** [comment]
I am using voice recognition so I apologize if there are any hilarious home and him.

I am looking at the change that you made 2 partial sequences and I think that the reason that it was written the way that it is is for performance reasons. Python strings are immutable objects and so everytime you apend a string the whole string has to be copied again. I think the new way that you wrote this is probably very slow for long reads.  

try doing a performance comparison between the two versions when using the scale to chromosome feature, a nucleotide display. If strengthen join internally uses a string app and then there is really no difference, but this will definitely be a lot faster if there is some way of just allocating the memory and reading it in only once.

**Comment by brendanwhitfield** [comment]
| "".join([]) | ""+="" |
|-------------|--------|
| 0.287       | 0.253  |
| 0.281       | 0.273  |
| 0.284       | 0.265  |
| 0.295       | 0.257  |

It's ~8% faster, because you don't have the `list` overhead, and `"".join([])` performs str cats anyways. It's also more human readable.

try it out for yourself:
https://gist.github.com/brendanwhitfield/18ef930fdcf1306c99b1

**Comment by josiahseaman** [comment]
Thanks for writing the gist.  I tested and modified it here: https://gist.github.com/josiahseaman/f9d5d611e5037e8f3d43

My tests in both python 2 and 3 showed a 100x slow down.  Worse, the speed difference gets bigger as numChunks gets bigger, meaning an exponential slowdown.  That means the two methods have a different [Big-O](http://en.wikipedia.org/wiki/Time_complexity).  

However, I'm looking at this more closely and I think you're still partially right.  I just added a third test that doesn't allocate [None] but still does the join() and that's faster.  Normally there's only a very small difference 1.2x, but sometimes it seems like the current strategy gets into thrashing and can be 100x slower.  This may be our server performance culprit!

Please modify your branch so that it fits something closer to this:

```python
    partialSequences = []
    for index in range(numChunks):
        partialSequences.append(sample_chunk)
 
    seq = "".join(partialSequences)
```

then I'll merge in the branch.  Thanks!

**Comment by brendanwhitfield** [comment]
I can't replicate the 100x figures with your script (tried on multiple computers), which is rather scary to be honest... Can confirm that using `append()` is slightly faster on average. Pull request updated

**Pull request merged**
